### ISSUE TITLE
Add surround characters in visual mode

### ISSUE THREAD

**Issue by vitorgalvao** [guillermooo/Vintageous_Plugin_Surround#4]
The feature I use most with surround (that is missing fom this plugin) is to select text in visual mode, press `S` (uppercase `s`), and then type the character I want it to be surrounded with ([see an example](http://asciinema.org/a/6291)).

The cases that have different opening and closing characters produce different result (although I don’t use both cases). In the example above, I pressed `)`, which produced `(a text)`, but if `(` had been pressed instead, the result would be `( a text )`.

**Comment by kuntau** [comment]
why this is closed. Pressing will delete the selection and put in insert mode instead of asking for surround input

**Comment by guillermooo** [comment]
Oops. Reopening.

**Comment by kuntau** [comment]
sorry again.. is this really fixed? because i still get the same behaviour

**Comment by guillermooo** [comment]
Please describe exactly what you do, what you get and what you expected instead.

**Comment by kuntau** [comment]
on Tim Pope surround plugin you can visually select a word with `vw` or `viw` or whatever then press `S` that is _capital s_ then the plugin will prompt for surround input.

I were to type `"` the the selection will surrounded with `"`. I also can type `<div` and the selection will be surrounded by `<div>Text</div>`

For the moment when press `S` _vintageous surround_ will delete the selection and put me in insert mode which wrong behaviour.

I hope u can understand. Thanks

**Comment by guillermooo** [comment]
This is working for me. How did you install the package? I might have not uploaded the latest version to Bitbucket (linked in the README).

**Comment by kuntau** [comment]
Yes. From bitbucket. How to install from github?

**Comment by guillermooo** [comment]
Try again now from BB.

**Comment by vitorgalvao** [comment]
It is working now for me, albeit “reversed” — pressing `(` should produce `( word )` and `)` should output `(word)`. Just referencing this in case you want to make it work as the vim plugin, since personally I do not mind.

**Comment by Lubomir-Russia** [comment]
Visual select works perfectly when the selection was started with "v" or a line selection with "Ctrl L". But it does not work when started with "V" - capital "V" to start vim-like line selection. In this case "S" will cause the substitute.

**Comment by vitorgalvao** [comment]
Project seems to be abandoned. Closing.
