### ISSUE TITLE
Package control

### ISSUE THREAD

**Issue by dvcrn** [guillermooo/Vintageous_Plugin_Surround#7]
Hello,

It'd be great to have this in package control. Many users, including me, use tools like boxen or dropbox to synchronize the Package Control settings file, which then installs dependent packages that are not present yet. 

Sadly this approach is with manual installs not that easy. 

Any estimate on when we can see a package control release?

**Comment by guillermooo** [comment]
Anyone could register this package with PC. It doesn't have to be me. :-)

If you do, please post back here.

**Comment by silouanwright** [comment]
+1. Can't get this package to work, so having it on PC would be helpful (I'm brand new to Sublime so I don't know my way around submitting it)

**Comment by asfaltboy** [comment]
@guillermooo any chance of tagging the current version (perhaps as 1.0.0 ; as this will be the first release on PC) ?

**Comment by dvcrn** [comment]
pinging @guillermooo again. We need a tag to add this to package control :(

**Comment by guillermooo** [comment]
0.1.0 added
